using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using Microsoft.CodeAnalysis;

namespace FlowNet.Collector.CodeAnalysis.Shared;

internal static class CommonCodeExtensions
{
    extension(StringBuilder sb)
    {
        public StringBuilder AppendTypeHeader(out int indent, INamedTypeSymbol type, bool fileLevelNamespace = true)
        {
            indent = type.GenerateTypeHeader(sb, fileLevelNamespace);
            return sb;
        }

        public StringBuilder AppendCommonHeader()
        {
            sb.AppendLine("// The file was generated by Flow.NET source generators, do NOT edit it manually.");
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using FlowNet.Core;");
            sb.AppendLine("using FlowNet.ComponentModel;");
            return sb;
        }

        public StringBuilder AppendExcludeFromCodeCoverageAttribute()
        {
            sb.AppendLine(Constants.ExcludeFromCodeCoverage);
            return sb;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        public StringBuilder AppendGeneratedCodeAttribute()
        {
            sb.Append("[global::System.CodeDom.Compiler.GeneratedCode(\"");
            var stackTrace = new StackTrace();
            var frame = stackTrace.GetFrame(1);
            var method = frame?.GetMethod();
            sb.Append(method?.DeclaringType?.FullName ?? "Unknown");
            sb.Append("\", \"");
            var assembly = Assembly.GetExecutingAssembly();
            sb.Append(assembly.GetName().Version?.ToString() ?? "Unknown");
            sb.AppendLine("\")]");
            return sb;
        }
    }
}
